apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense  
data:
  DB_HOST: mysql
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # labels of deployment resource
  labels:
    app: backend
    tier: app
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: app
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: nginx
        image: omparameswara123/backend:1.0.0
        resources:
        # Always ensure requests are less than or equal(<=) to limits
          requests:
            cpu: "100m"
            memory: "2Gi"
          limits:
            cpu: "200m"
            memory: "3Gi"
        envFrom:
        - ConfigMapKeyRef:
            name: backend
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector: # labels are used as selectors
    app: backend
    tier: app
    project: expense
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080