apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # labels of deployment resource
  labels:
    app: mysql
    tier: database
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: database
        project: expense
    spec:
      containers:
      - name: nginx
        image: omparameswara123/mysql:1.0.0
        readinessProbe:
          tcpSocket:
            port: 3306
          intialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          intialDelaySeconds: 15
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector: # labels are used as selectors
    app: mysql
    tier: database
    project: expense
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306